version: "3"
services: 
  pg-tasks:
    restart: always
    container_name: pg-tasks
    image: postgres:9.6
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=tasks
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password